# -*- coding: utf-8 -*-
"""Start.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17oH0hVYuj2aUlRht4JAW23voiKOAoRm-
"""

# %cd /content
# !curl -L "https://public.roboflow.com/ds/8nhfMDr86Z?key=WnpUWjqvrH" > roboflow.zip; unzip roboflow.zip; rm roboflow.zip

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!git clone https://github.com/ultralytics/yolov5.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolov5/
!pip install -r requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %cat /content/drive/MyDrive/SNUBH_AI_project/Echocardiogram_detection/data.yaml

# Commented out IPython magic to ensure Python compatibility.
# %cd /
from glob import glob

img_list = glob('/content/drive/MyDrive/SNUBH_AI_project/Echocardiogram_detection/images/*.jpg')
text_list = glob('/content/drive/MyDrive/SNUBH_AI_project/Echocardiogram_detection/labels/*.txt')

print(len(img_list), len(text_list))

img_list[:5]

from sklearn.model_selection import train_test_split

train_img_list, val_img_list = train_test_split(img_list, test_size=0.2, random_state=42)

print(len(train_img_list), len(val_img_list))

with open('/content/drive/MyDrive/SNUBH_AI_project/Echocardiogram_detection/train.txt', 'w') as f:
    f.write('\n'.join(train_img_list) + '\n')

with open('/content/drive/MyDrive/SNUBH_AI_project/Echocardiogram_detection/val.txt', 'w') as f:
    f.write('\n'.join(val_img_list) + '\n')

import yaml

with open('/content/drive/MyDrive/SNUBH_AI_project/Echocardiogram_detection/data.yaml', 'r') as f:
    data = yaml.load(f)

print(data)

data['train'] = '/content/drive/MyDrive/SNUBH_AI_project/Echocardiogram_detection/train.txt'
data['val'] = '/content/drive/MyDrive/SNUBH_AI_project/Echocardiogram_detection/val.txt'

with open('/content/drive/MyDrive/SNUBH_AI_project/Echocardiogram_detection/data.yaml', 'w') as f:
    yaml.dump(data, f)

print(data)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolov5/

!python train.py --img 416 --batch 32 --epochs 25 --data /content/drive/MyDrive/SNUBH_AI_project/Echocardiogram_detection/data.yaml --cfg /content/yolov5/models/yolov5x.yaml --weights yolov5x.pt --name Echocardio

from IPython.display import Image
import os

val_img_path = val_img_list[42]

!python detect.py --weights /content/yolov5/runs/train/Echocardio/weights/best.pt --img 416 --conf 0.8 --source "{val_img_path}"
Image(os.path.join('/content/yolov5/inference/output', os.path.basename(val_img_path)))

# Commented out IPython magic to ensure Python compatibility.
# %%time
# !python detect.py --weights /content/yolov5/runs/train/Echocardio/weights/best.pt --img 416 --conf 0.8 --source /content/drive/MyDrive/SNUBH_AI_project/Echocardiogram_detection/Myocardium_test_set2.mp4

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir /content/yolov5/runs/

